"""table post add field abstract title

Revision ID: f72f550437
Revises: 51f5ccfba190
Create Date: 2016-02-01 19:11:54.617795

"""

# revision identifiers, used by Alembic.
revision = 'f72f550437'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
